<a href="https://colab.research.google.com/github/douglassesi/Python/blob/master/Aula_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [2]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: ignored

In [3]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [4]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64
8


In [7]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print(data4)
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[6.  7.5]
 [8.  1. ]]


In [9]:
data6 = np.arange(15)
print(data6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [11]:
arr1 + arr2

ValueError: ignored

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


In [0]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

In [0]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

## Operações entre arrays e escalares

In [13]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Array elevado ao quadrado: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Array elevado ao quadrado: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [0]:
arr = [2,14,3,6,8,3,10,222,4]
arr = np.array(arr)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

In [0]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2]) #igual a print(arr2d[0, 2])

[7 8 9]
3


In [17]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])


[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]



## Transposição

In [18]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [19]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

----- flatten() -----

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

----- ravel() -----

[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Funções Universais

In [20]:
arr = np.arange(10)
print(arr)
np.sqrt(arr) #raiz quadrada
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [0]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
import timeit

In [30]:
%timeit result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
#result

The slowest run took 6.47 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.25 µs per loop


In [49]:
%timeit result = np.where(cond, xarr, yarr)
#result
####ESSA É MUITO BOA####

The slowest run took 24.25 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.34 µs per loop


In [32]:
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[ 0.14587057 -1.09386912  1.43625817  0.62016911]
 [ 0.40504988  0.9291284   0.57256244 -0.18296643]
 [ 0.35394285  0.98535403  0.73182631 -0.22017878]
 [ 0.40182261 -1.09544769 -1.69790943  1.95884076]]
[[ 2 -2  2  2]
 [ 2  2  2 -2]
 [ 2  2  2 -2]
 [ 2 -2 -2  2]]
[[ 2.         -1.09386912  2.          2.        ]
 [ 2.          2.          2.         -0.18296643]
 [ 2.          2.          2.         -0.22017878]
 [ 2.         -1.09544769 -1.69790943  2.        ]]


In [33]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean()) #ou np.mean(arr)
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))

[[ 0.51165693  1.37642333 -0.07752341 -2.5807035 ]
 [ 0.41656808  0.82516157  0.02858185  1.57034672]
 [ 3.66844281 -1.89385992  0.25046712  0.50390284]
 [-2.4101894   0.39412275 -0.45344563 -0.33612331]
 [-0.77469912 -2.0529362   0.51365525  0.13992346]]
-0.019011389326169453
-0.38022778652338907
[-0.19253666  0.71016455  0.63223821 -0.7014089  -0.54351415]
[ 1.41177929 -1.35108847  0.26173519 -0.7026538 ]


## Álgebra Linear

In [34]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]


In [35]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print(mat)
print(inv(mat)) #inversa

[[ 0.68995219  2.68057185  1.79745888 -0.54917627  1.83047283]
 [ 0.22557209 -0.23811745  0.29885861  1.60416305 -0.16915563]
 [ 0.08993305  1.70289186  1.59430946  0.79962481  1.40909689]
 [ 0.58405026 -0.89063725 -1.21955837 -1.93998247 -0.08343679]
 [ 1.17289387 -0.19667257 -0.341166    0.34342655  0.68427987]]
[[ 2.25179948  1.19804706  0.33852106 -0.67538265  2.10536271]
 [ 1.19804706 10.97392087  8.61527295  1.16786697  7.28626531]
 [ 0.33852106  8.61527295  7.46571443  3.01590197  5.35448554]
 [-0.67538265  1.16786697  3.01590197  7.39580729  0.24700916]
 [ 2.10536271  7.28626531  5.35448554  0.24700916  5.83999908]]
[[  4.36247564  -4.22320513   8.30723841  -2.19447668  -3.82742057]
 [ -4.22320513  21.26836897 -26.44793204   7.07644989  -1.06309582]
 [  8.30723841 -26.44793204  36.20375092  -9.73554757  -2.77924559]
 [ -2.19447668   7.07644989  -9.73554757   2.76161983   0.77157227]
 [ -3.82742057  -1.06309582  -2.77924559   0.77157227   5.39297202]]


## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [36]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.8790011 , 0.45553675, 0.7182895 , 0.86650915])

In [37]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(42) # reset seed
print(np.random.random())

0.3745401188473625
0.3745401188473625


In [38]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

array([3, 9, 0, 8, 5, 2, 1, 6, 4, 7])

## Vectorize

In [39]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: ignored

In [40]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [41]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [42]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


## Outros Métodos

In [0]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

In [0]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place
print(arr)

In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [44]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## TODO Section

### Manipulação de Arrays

Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B

In [61]:
# TODO: sua resposta aqui
import numpy as np
import timeit
a = [1,4,2,6,5,7,3,0]
b = [3,2,0,9,8,7]

retorno = np.setdiff1d(a,b)

print(retorno)

[1 4 5 6]


### Manipulando arrays de acordo com valores escalares

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [0]:
# TODO: sua resposta aqui
def interval (vetor, x=6, y=20):
    return np.sort(vetor[(vetor > x) & (vetor <y)])

# Pandas

## Estrutura de Dados

In [65]:
from pandas import Series, DataFrame
import pandas as pd
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [66]:
print(obj.values)
print(obj.index) #obj.index.values

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [67]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [68]:
import numpy as np
print(obj2[(obj2 > 0) & (obj2 < 5)])
print(obj2 * 2)
print(np.exp(obj2))

d    4
c    3
dtype: int64
d     8
b    14
a   -10
c     6
dtype: int64
d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64


In [69]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [70]:
states = ['Oregon', 'Texas','California', 'Ohio']
obj4 = Series(sdata, index=states)
obj4

Oregon        16000.0
Texas         71000.0
California        NaN
Ohio          35000.0
dtype: float64

In [0]:
print(pd.isnull(obj4)) # == obj4.isnull()
print(pd.notnull(obj4))

In [0]:
print(obj3)
print(obj4)
obj3 + obj4

In [0]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

In [0]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

In [71]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [72]:
df2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                index=['one', 'two', 'three', 'four', 'five'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [73]:
print(df['state'])
print(df.year)

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object
0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64


In [74]:
print(df2.loc['four']) #label
print(df.iloc[0]) #int

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object
state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object


In [0]:
df2['debt'] = np.arange(5)

In [77]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df2['debt'] = val
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [78]:
df2['eastern'] = df2.state == 'Ohio'
df2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [79]:
del df2['eastern']
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [80]:
df.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9]], dtype=object)

In [0]:
obj = Series(range(3), index=['a', 'b', 'c'])
obj.index.values

In [0]:
print('state' in df2.columns)
print(0 in df.index)

## Aplicação de Função e Mapeamento

In [0]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [81]:
df = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
np.abs(df) #retorna valor absoluto

b         d         e
Utah    0.464024  0.057027  0.275930
Ohio    1.494515  0.566821  2.303374
Texas   1.377001  1.187387  0.079393
Oregon  0.107969  0.506951  1.125589

In [82]:
f = lambda x: x.max() - x.min()
print(df.apply(f))
print(df.apply(f, axis=1))

b    1.958539
d    1.754207
e    3.428964
dtype: float64
Utah      0.739953
Ohio      3.797889
Texas     2.564388
Oregon    1.017621
dtype: float64


In [84]:
def f2(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

df.apply(f2)

b         d         e
min -0.464024 -1.187387 -2.303374
max  1.494515  0.566821  1.125589

In [0]:
format2 = lambda x: '%.2f' % x
df.applymap(format2)

## Ordenação e Ranking

In [85]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
df2 = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
print(obj)
print(df2)
print(obj.sort_index())
print(df2.sort_index())
print(df2.sort_index(axis=1))

d    0
a    1
b    2
c    3
dtype: int64
       d  a  b  c
three  0  1  2  3
one    4  5  6  7
a    1
b    2
c    3
d    0
dtype: int64
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4


In [86]:
obj = Series([4, 7, -3, 2])
obj.sort_values() #igual para pandas

2   -3
3    2
0    4
1    7
dtype: int64

In [87]:
df3 = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(df3)
print(df3.sort_index(by='b'))
print(df3.sort_index(by=['a','b']))

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1
   b  a
2 -3  0
0  4  0
3  2  1
1  7  1


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  after removing the cwd from sys.path.


In [90]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'nota': [8, 7.5, 7.5, 10, 5]}
df4 = DataFrame(data)
print(df4)
df4['rank'] = df4['nota'].rank(ascending=0)
df4.sort_values('rank')

    name  nota
0  Jason   8.0
1  Molly   7.5
2   Tina   7.5
3   Jake  10.0
4    Amy   5.0


name  nota  rank
3   Jake  10.0   1.0
0  Jason   8.0   2.0
1  Molly   7.5   3.5
2   Tina   7.5   3.5
4    Amy   5.0   5.0

## Sumarização e Estatística Descritiva

In [93]:
df5 = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
print(df5)
print(df5.sum())
print(df5.sum(axis=1))
print(df5.count())
print(df5.size)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
one    3
two    2
dtype: int64
8


In [94]:
df5.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [95]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [96]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

## Manipulação de Valores Faltantes 

In [97]:
string_data = Series(['laranja', 'uva', np.nan, 'abacate'])
print(string_data)
print(string_data.isnull())
string_data[0] = None
print(string_data.isnull())

0    laranja
1        uva
2        NaN
3    abacate
dtype: object
0    False
1    False
2     True
3    False
dtype: bool
0     True
1    False
2     True
3    False
dtype: bool


In [0]:
data = DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                  [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
cleaned = data.dropna()
print('\n',cleaned)
data.dropna(how='all')

In [0]:
print(data.fillna(0))
print(data.fillna(data.mean()))

## TODO Section

### Manipulação de DataFrame

        > Crie, a partir do dicionário abaixo, um DataFrame cujo index seja os valores da variável labels
        > encontre a média dos valores da coluna age e preencha os valores faltantes dessa coluna com o valor da média
        > crie uma nova coluna chamada 'rank', que mostre os animais que receberam mais visitas
        > qual o animal que recebeu a maior quantidade de visitas?

In [0]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Exercicio 1 -   > Crie, a partir do dicionário abaixo, um DataFrame cujo index seja os valores da variável labels

In [111]:
# TODO: sua resposta aqui


animais = DataFrame(data, index = labels)
print(animais)



  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


Exercicio 2 -encontre a média dos valores da coluna age e preencha os valores faltantes dessa coluna com o valor da média

In [117]:
animais = animais.fillna(animais.age.mean())
print(animais)


  animal     age  visits priority
a    cat  2.5000       1      yes
b    cat  3.0000       3      yes
c  snake  0.5000       2       no
d    dog  3.4375       3      yes
e    dog  5.0000       2       no
f    cat  2.0000       3       no
g  snake  4.5000       1       no
h    cat  3.4375       1      yes
i    dog  7.0000       2       no
j    dog  3.0000       1       no


Exercício 3 - crie uma nova coluna chamada 'rank', que mostre os animais que receberam mais visitas

In [139]:
animais['rank'] = animais['visits'].rank(ascending=0)
animais.sort_values('rank')

animal     age  visits priority  rank
b    cat  3.0000       3      yes   2.0
d    dog  3.4375       3      yes   2.0
f    cat  2.0000       3       no   2.0
c  snake  0.5000       2       no   5.0
e    dog  5.0000       2       no   5.0
i    dog  7.0000       2       no   5.0
a    cat  2.5000       1      yes   8.5
g  snake  4.5000       1       no   8.5
h    cat  3.4375       1      yes   8.5
j    dog  3.0000       1       no   8.5

Exercício 4 -qual o animal que recebeu a maior quantidade de visitas?

In [142]:
animais[animais['visits'] == animais['visits'].max()]


animal     age  visits priority  rank
b    cat  3.0000       3      yes   2.0
d    dog  3.4375       3      yes   2.0
f    cat  2.0000       3       no   2.0